### ISSUE TITLE
SteamWorld Dig 2

### ISSUE THREAD

**Issue by Edpow** [strato-emu/compat-list#510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Tested Build

1174

### Android Version

11

### SoC type

Snapdragon

### Device GSMArena link

https://m.gsmarena.com/motorola_moto_g_5g_plus-10307.php

### Game Behaviour

- Game enter in-game 
- Game freezes randomly.
- Needs disable Triple Buffering to minimize freezes.
- The speed is not constant.
- Some graphical glitches, flicks.

![Freezes before mais screen](https://user-images.githubusercontent.com/71780819/172030270-754f8684-5d18-4b70-8d7b-93e1f33dad59.png)
![In Game after many tries](https://user-images.githubusercontent.com/71780819/172030271-aa8098ab-1571-4a75-b30d-24ab512f4654.png)
![Freeze in main screen](https://user-images.githubusercontent.com/71780819/172030340-30ddb2d4-cd34-44d7-b9c9-c9002aa77aa5.png)
[Gameplay Video](https://user-images.githubusercontent.com/71780819/172158425-2ad9da72-9550-48a9-97b3-4cfb19a82b9d.mp4)

### Is Log Level is set to 'Info'?

- [X] Yes

**Comment by Edpow** [comment]
[archive.zip](https://github.com/skyline-emu/skyline-games-list/files/8815879/archive.zip)

**Comment by Edpow** [comment]
The log button is not working for me... I compress de the files in the log folder in the in internal of skyline

**Comment by Edpow** [comment]
When I click in button, the skyline closes.
![Screenshot_20220601-120659-595](https://user-images.githubusercontent.com/71780819/171449891-4bd973eb-fb31-4aa0-b300-ef739ed4ba92.png)

**Comment by Ragul32** [comment]
> When I click in button, the skyline closes. ![Screenshot_20220601-120659-595](https://user-images.githubusercontent.com/71780819/171449891-4bd973eb-fb31-4aa0-b300-ef739ed4ba92.png)

Fixed in new build

**Comment by K11MCH1** [comment]
Retest on latest build. Log importer fixed.

**Comment by Edpow** [comment]
![Screenshot_20220604-202712.png](https://user-images.githubusercontent.com/71780819/172030027-41f68533-0501-4014-9ab9-999259cc82d9.png)
Still freezes randomly.

**Comment by Edpow** [comment]
![Screenshot_20220604-202635.png](https://user-images.githubusercontent.com/71780819/172030093-11180981-8c2a-4e99-aaa0-5c8260249857.png)

**Comment by Theus061** [comment]
Tested on build #1314

[Device: OnePlus 7 Pro](https://www.google.com/amp/s/m.gsmarena.com/oneplus_7_pro-ampp-9689.php)
Android 11
SoC: SnapDragon

Playable around 60 FPS, no audio issues, small shading glitch inside caves. Turnip v12 + handheld + no triple buffering
![Screenshot_20220820-124304_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/108691734/185758037-c1c5bc88-9eff-47ec-80d4-4a179d6fb0e0.jpg)
![Screenshot_20220820-124910_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/108691734/185758046-b4c6cc1c-9a9e-46c7-83a3-3557989c5858.jpg)
![Screenshot_20220820-133308_fcf072b9e4efc4ce5ca3e36691a7c3c6](https://user-images.githubusercontent.com/108691734/185758050-28b990c5-1c42-4aff-984a-9d39814ea66e.jpg)

https://user-images.githubusercontent.com/108691734/185758052-c7e48eed-4891-4f4b-9193-c612bc5ce1b3.mp4

Log: [steamworlddig2.txt](https://drive.google.com/file/d/1AXhFp2q1o9HK66qVr4uzSG1ZejHuneG3/view?usp=drivesdk)
